# Copyright (c) 2023 Maxim [maxirmx] Samsonov (https://sw.consulting)
# All rights reserved.
# This file is a part of rucades

name: Build-and-test

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.ref_name }}'
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Linux Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.7.8'
          - '3.1.7'
          - '3.2.11'
          - '3.3.11'
          - '3.4.9'
          - '4.0.5'

    steps:
    - uses: actions/checkout@v3

    - name: Install packages
      run: |
        sudo apt -y update
        sudo apt -y install cmake build-essential libboost-dev unzip wget

    - name: Install CSP and SDK
      run: |
        pushd sdk
        tar xvf linux-amd64_deb.tgz
        pushd linux-amd64_deb
        sudo ./install.sh
        sudo apt install ./lsb-cprocsp-devel_5.0*.deb
        popd
        tar xvf cades-linux-amd64.tar.gz
        pushd cades-linux-amd64
        sudo apt install ./cprocsp-pki-cades*.deb
        popd
        popd

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Fix permissions
      run: chmod a+x bin/*

    - name: Build and test
      run: bundle exec rake

  build-macos:
    runs-on: macos-latest
    name: macOS Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.1.7'
          - '3.2.11'
          - '3.3.11'
          - '3.4.9'
          - '4.0.5'

    steps:
    - uses: actions/checkout@v3

    - name: Install packages
      run: brew install boost cmake

    - name: Install CSP and SDK
      run: |
        pushd sdk
        sudo installer -pkg macos-cprocsp.pkg -target /
        popd

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Fix permissions
      run: chmod a+x bin/*

    - name: Build and test
      run: bundle exec rake
